'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='worknote_state_v1';
const APP_VERSION='15.0.0';
const REPORT_DRAFT_STORE='worknote_report_drafts_v1';
const GEMINI_KEY_STORE='worknote_gemini_api_key_v1';
const V15_CLEANUP_STORE='worknote_v15_cleanup_done';
const DEFAULT_GEMINI_MODEL='gemini-3.1-flash-lite';
const pad=n=>String(n).padStart(2,'0');
const isoDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const nowISO=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const DEFAULT={
 version:1,profile:{name:'ヒガ'},settings:{notifications:false,notificationMaster:true,carryMode:'nextShift',lastBackup:null,notificationLog:{},reportReminderEnabled:true,reportReminderTime:'22:00'},
 ai:{enabled:true,mode:'local',endpoint:'',automationLevel:2,lastRun:null,inbox:[],chat:[],rules:[],weekly:[],staffInsights:{},lastDigestKey:'',connectionStatus:'未接続',lastError:'',model:DEFAULT_GEMINI_MODEL},
 shiftTypes:[{id:'early',name:'早番',start:'09:30',end:'18:30',color:'#7dc6ff'},{id:'late',name:'遅番',start:'11:00',end:'20:00',color:'#9e8cff'},{id:'full',name:'フル',start:'09:30',end:'20:00',color:'#55c9a5'},{id:'off',name:'休み',start:'',end:'',color:'#aeb9c5'}],
 shifts:{},
 rules:[
  {id:uid(),title:'セルナビ更新',enabled:true,scope:'work',timing:'退勤前',notify:false},
  {id:uid(),title:'クレカ実績更新',enabled:true,scope:'work',timing:'退勤前',notify:false},
  {id:uid(),title:'当日実績確認',enabled:true,scope:'work',timing:'退勤前',notify:false},
  {id:uid(),title:'未完了案件確認',enabled:true,scope:'work',timing:'退勤前',notify:false},
  {id:uid(),title:'予約内容の確認',enabled:true,scope:'early',timing:'出勤時',notify:false}
 ],tasks:[],notes:[],events:[],focus:{},dayClosed:{},trash:[]
};
let state=load();
state.settings=Object.assign({},clone(DEFAULT.settings),state.settings||{});
state.trash=state.trash||[];
state.ai=Object.assign({},clone(DEFAULT.ai),state.ai||{});state.ai.inbox=state.ai.inbox||[];state.ai.chat=state.ai.chat||[];state.ai.rules=state.ai.rules||[];state.ai.weekly=state.ai.weekly||[];state.ai.staffInsights=state.ai.staffInsights||{};if(state.ai.mode==='openai'||state.ai.mode==='gemini')state.ai.mode='geminiDirect';state.ai.model=state.ai.model||DEFAULT_GEMINI_MODEL;
state.notes.forEach(n=>{if(n.type==='fixed'||n.type==='report')n.type='normal'});
if(!localStorage.getItem(V15_CLEANUP_STORE)){const today=isoDate(new Date());state.tasks=state.tasks.filter(t=>!t.date||t.date>=today);state.ai.inbox=[];state.ai.lastDigestKey='';localStorage.setItem(V15_CLEANUP_STORE,'1')}save();
let currentView='home', calCursor=new Date(), selectedDate=isoDate(new Date());
let swRegistration=null, updateReloading=false;
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE));return x?Object.assign(clone(DEFAULT),x):clone(DEFAULT)}catch{return clone(DEFAULT)}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(t,actionLabel='',action=null,duration=2200){const e=$('#toast');e.innerHTML=`<span>${esc(t)}</span>${actionLabel?`<button id="toastAction">${esc(actionLabel)}</button>`:''}`;e.classList.remove('hidden');clearTimeout(toast.t);if(actionLabel&&$('#toastAction'))$('#toastAction').onclick=()=>{clearTimeout(toast.t);e.classList.add('hidden');action?.()};toast.t=setTimeout(()=>e.classList.add('hidden'),duration)}
function formatDate(d){return new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(d)}
function shiftByDate(date){const id=state.shifts[date];return state.shiftTypes.find(x=>x.id===id)}
function isWorkShift(s){return s&&s.id!=='off'}
function ensureTasksForDate(date){const shift=shiftByDate(date);if(!isWorkShift(shift))return;
 state.rules.filter(r=>r.enabled&&(r.scope==='work'||r.scope===shift.id||r.scope==='daily')).forEach(r=>{
  const key=`${date}:${r.id}`;
  if(!state.tasks.some(t=>t.autoKey===key))state.tasks.push({id:uid(),title:r.title,date,done:false,createdAt:nowISO(),auto:true,autoKey:key,ruleId:r.id,timing:r.timing,carriedFrom:null});
 });save()}
function reconcileDate(date){const shift=shiftByDate(date);const allowed=new Set();if(isWorkShift(shift))state.rules.filter(r=>r.enabled&&(r.scope==='work'||r.scope===shift.id||r.scope==='daily')).forEach(r=>allowed.add(`${date}:${r.id}`));
 state.tasks=state.tasks.filter(t=>{if(t.date!==date||!t.auto||t.done)return true;if(t.manuallyEdited)return true;return allowed.has(t.autoKey)});ensureTasksForDate(date);save()}
function nextWorkDate(from){let d=new Date(from+'T12:00:00');for(let i=0;i<370;i++){d.setDate(d.getDate()+1);const k=isoDate(d);if(isWorkShift(shiftByDate(k)))return k}return null}
function render(){ensureTasksForDate(isoDate(new Date()));$('#headerDate').textContent=formatDate(new Date());
 const titles={home:'WORKNOTE',notes:'メモ',calendar:'カレンダー',ai:'AI副店長補佐',settings:'設定'};$('#pageTitle').textContent=titles[currentView];
 $$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${currentView}`).classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));
 ({home:renderHome,notes:renderNotes,calendar:renderCalendar,ai:renderAI,settings:renderSettings}[currentView])();
}
function renderHome(){runAIAutomation(false);const date=isoDate(new Date()),tasks=state.tasks.filter(t=>t.date===date),done=tasks.filter(t=>t.done).length,notes=state.notes.filter(n=>n.date===date&&!n.archived),reports=notes.filter(n=>n.type==='dailyReport').length,shift=shiftByDate(date),aiOpen=state.ai.inbox.filter(x=>x.status==='open');
 $('#view-home').innerHTML=`<section class="hero"><div class="hero-row"><div><h2>${greeting()}、${esc(state.profile.name)}さん</h2><p>${formatDate(new Date())}</p></div><div class="shift-pill">${shift?`${esc(shift.name)}${shift.start?` ${shift.start}〜${shift.end}`:''}`:'シフト未登録'}</div></div><div class="stats"><div class="stat"><strong>${done}/${tasks.length}</strong><span>タスク</span></div><div class="stat"><strong>${notes.length}</strong><span>今日のメモ</span></div><div class="stat"><strong>${reports}</strong><span>日報</span></div></div></section>
 <section class="section"><button class="card ai-home-card" id="openAI"><div class="ai-card-top"><div><span class="ai-badge">AI副店長補佐</span><h2>${aiOpen.length?`対応候補が${aiOpen.length}件あります`:'今日の確認は完了しています'}</h2></div><span class="ai-arrow">›</span></div><div class="ai-home-summary">${aiOpen.slice(0,3).map(x=>`<div><b>${esc(x.kindLabel||'提案')}</b> ${esc(x.title)}</div>`).join('')||'<div>予定・タスク・日報・MTGを自動確認しています。</div>'}</div></button></section>
 <section class="section"><div class="section-head"><h2>🎯 今日の重点</h2></div><div class="card focus-card"><textarea id="focusInput" rows="2" placeholder="今日いちばん大切にすること">${esc(state.focus[date]||'')}</textarea></div></section>
 <section class="section"><div class="section-head"><h2>今日のタスク</h2><button class="link-btn" id="addTaskBtn">＋追加</button></div>${tasks.length?tasks.sort((a,b)=>a.done-b.done).map(taskHTML).join(''):'<div class="empty">今日のタスクはありません</div>'}</section>
 <section class="section"><div class="section-head"><h2>未整理メモ</h2><button class="link-btn" data-goto="notes">すべて見る</button></div>${notes.filter(n=>n.type==='inbox').slice(0,3).map(noteHTML).join('')||'<div class="empty">思いついたことを右下の＋からメモできます</div>'}</section>
 <section class="section"><button class="primary" id="closeDayBtn" style="width:100%">本日の業務を終了</button></section>`;
 $('#openAI').onclick=()=>switchView('ai');$('#focusInput').addEventListener('change',e=>{state.focus[date]=e.target.value.trim();save()});$('#addTaskBtn').onclick=()=>openTaskModal(date);$('#closeDayBtn').onclick=()=>openCloseDay(date);$$('[data-goto]').forEach(x=>x.onclick=()=>switchView(x.dataset.goto));bindTaskButtons();bindNoteMenus();}
function greeting(){const h=new Date().getHours();return h<11?'おはようございます':h<17?'こんにちは':'こんばんは'}
function taskHTML(t){return `<div class="card task ${t.done?'done':''}" data-task="${t.id}"><button class="check">${t.done?'✓':''}</button><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.timing||'')}${t.priority?'・優先度 '+esc(t.priority):''} ${t.auto?'・自動':''}${t.carriedFrom?'・繰り越し':''}${t.doneAt?'・'+new Date(t.doneAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})+'完了':''}</div></div><button class="more-btn">…</button></div>`}
function bindTaskButtons(){$$('[data-task]').forEach(el=>{const id=el.dataset.task;$('.check',el).onclick=()=>toggleTask(id);$('.more-btn',el).onclick=()=>openTaskMenu(id)})}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;t.doneAt=t.done?nowISO():null;save();render();toast(t.done?'完了しました':'未完了に戻しました')}
function openTaskMenu(id){const t=state.tasks.find(x=>x.id===id);openModal(`<h2>${esc(t.title)}</h2><div class="btn-row"><button class="secondary" id="editTask">編集</button><button class="secondary" id="moveTask">日付変更</button><button class="danger" id="deleteTask">削除</button></div>`);$('#editTask').onclick=()=>openTaskModal(t.date,t);$('#moveTask').onclick=()=>openMoveTask(t);$('#deleteTask').onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==id);save();closeModal();render();toast('削除しました')}}
function openTaskModal(date,t=null){openModal(`<h2>${t?'タスクを編集':'タスクを追加'}</h2><div class="field"><label>内容</label><input id="taskTitle" value="${esc(t?.title||'')}"></div><div class="grid2"><div class="field"><label>日付</label><input id="taskDate" type="date" value="${t?.date||date}"></div><div class="field"><label>タイミング</label><select id="taskTiming"><option>終日</option><option>出勤時</option><option>昼</option><option>退勤前</option></select></div></div><div class="btn-row"><button class="secondary" id="cancel">キャンセル</button><button class="primary" id="saveTask">保存</button></div>`);$('#taskTiming').value=t?.timing||'終日';$('#cancel').onclick=closeModal;$('#saveTask').onclick=()=>{const title=$('#taskTitle').value.trim();if(!title)return toast('内容を入力してください');if(t){t.title=title;t.date=$('#taskDate').value;t.timing=$('#taskTiming').value;t.manuallyEdited=true}else state.tasks.push({id:uid(),title,date:$('#taskDate').value,done:false,createdAt:nowISO(),auto:false,timing:$('#taskTiming').value});save();closeModal();render();toast('保存しました')}}
function openMoveTask(t){openModal(`<h2>タスクを移動</h2><button class="card" id="nextShift" style="width:100%;text-align:left">次回出勤日へ</button><button class="card" id="tomorrow" style="width:100%;text-align:left">明日へ</button><div class="field"><label>日付を指定</label><input type="date" id="moveDate" value="${t.date}"></div><button class="primary" id="moveSave" style="width:100%">移動</button>`);$('#nextShift').onclick=()=>move(nextWorkDate(t.date));$('#tomorrow').onclick=()=>{const d=new Date(t.date+'T12:00:00');d.setDate(d.getDate()+1);move(isoDate(d))};$('#moveSave').onclick=()=>move($('#moveDate').value);function move(date){if(!date)return toast('次の出勤日が未登録です');t.carriedFrom=t.date;t.date=date;save();closeModal();render();toast('移動しました')}}
function openCloseDay(date){const undone=state.tasks.filter(t=>t.date===date&&!t.done);openModal(`<h2>本日の終了確認</h2>${undone.length?`<div class="warning">未完了タスクが${undone.length}件あります。次回出勤日へ繰り越しますか？</div>${undone.map(t=>`<div class="list-row"><span>□</span><div class="grow">${esc(t.title)}</div></div>`).join('')}`:'<div class="card">今日のタスクはすべて完了しています。</div>'}<div class="btn-row"><button class="secondary" id="cancel">戻る</button>${undone.length?'<button class="primary" id="carry">繰り越して終了</button>':'<button class="primary" id="finish">終了する</button>'}</div>`);$('#cancel').onclick=closeModal;const finish=()=>{state.dayClosed[date]=nowISO();save();closeModal();render();toast('本日の記録を保存しました')};if($('#finish'))$('#finish').onclick=finish;if($('#carry'))$('#carry').onclick=()=>{const next=nextWorkDate(date);if(!next)return toast('次の出勤日を先に登録してください');undone.forEach(t=>{t.carriedFrom=t.date;t.date=next});finish()}}
function noteDisplayTitle(n){if(n.title)return n.title;const first=(n.text||'').split(/\n/).find(Boolean)||'無題のメモ';return first.length>46?first.slice(0,46)+'…':first}
function noteHTML(n){return `<div class="card note-card" data-note="${n.id}"><button class="more-btn note-menu">…</button><h3>${n.pinned?'<span class="pin">★</span> ':''}${esc(noteDisplayTitle(n))}</h3><div class="note-meta"><span>${new Date(n.createdAt).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span><span class="tag">${labelType(n.type)}</span>${n.staff?`<span class="tag">${esc(n.staff)}</span>`:''}</div></div>`}
function labelType(t){return({inbox:'受信箱',normal:'通常',staff:'スタッフ',dailyReport:'日報',meeting:'MTG'}[t]||'メモ')}
function renderNotes(){const filter=renderNotes.filter||'all',q=renderNotes.q||'';let notes=state.notes.filter(n=>!n.archived);if(filter!=='all')notes=notes.filter(n=>n.type===filter);if(q)notes=notes.filter(n=>(n.text||'').toLowerCase().includes(q.toLowerCase())||(n.title||'').toLowerCase().includes(q.toLowerCase())||(n.staff||'').includes(q));
 $('#view-notes').innerHTML=`<div class="search-box"><input id="noteSearch" placeholder="メモを検索" value="${esc(q)}"></div><div class="chip-row">${[['all','すべて'],['inbox','受信箱'],['normal','通常'],['dailyReport','日報'],['meeting','MTG'],['staff','スタッフ']].map(([k,v])=>`<button class="chip ${filter===k?'active':''}" data-filter="${k}">${v}</button>`).join('')}</div><section class="section">${notes.sort((a,b)=>(b.updatedAt||b.createdAt).localeCompare(a.updatedAt||a.createdAt)).map(noteHTML).join('')||'<div class="empty">該当するメモはありません</div>'}</section>`;
 $('#noteSearch').oninput=e=>{renderNotes.q=e.target.value;renderNotes()};$$('[data-filter]').forEach(b=>b.onclick=()=>{renderNotes.filter=b.dataset.filter;renderNotes()});bindNoteMenus()}
function bindNoteMenus(){$$('[data-note]').forEach(el=>{const id=el.dataset.note;el.onclick=e=>{if(e.target.closest('.note-menu'))return;openNoteViewer(id)};$('.note-menu',el).onclick=e=>{e.stopPropagation();openNoteMenu(id)}})}
function deleteNote(id){const index=state.notes.findIndex(x=>x.id===id);if(index<0)return;const removed=state.notes.splice(index,1)[0];state.trash.push({kind:'note',item:removed,deletedAt:nowISO()});save();closeModal();render();toast('削除しました','元に戻す',()=>{const hit=state.trash.findIndex(x=>x.item?.id===id);if(hit>=0){state.notes.push(state.trash.splice(hit,1)[0].item);save();render();toast('元に戻しました')}},5000)}
function confirmDeleteNote(id){const n=state.notes.find(x=>x.id===id);if(!n)return;openModal(`<h2>削除の確認</h2><div class="warning">「${esc(noteDisplayTitle(n))}」を削除しますか？</div><div class="btn-row"><button class="secondary" id="cancelDelete">キャンセル</button><button class="danger" id="confirmDelete">削除する</button></div>`);$('#cancelDelete').onclick=closeModal;$('#confirmDelete').onclick=()=>deleteNote(id)}
function openNoteMenu(id){const n=state.notes.find(x=>x.id===id);if(!n)return;openModal(`<h2>メモの操作</h2><div class="list-row"><button class="secondary grow" id="viewNote">読む</button></div><div class="list-row"><button class="secondary grow" id="editNote">編集</button></div>${n.type!=='meeting'?'<div class="list-row"><button class="secondary grow" id="taskify">タスクにする</button></div>':''}<div class="list-row"><button class="danger grow" id="deleteNote">削除</button></div>`);$('#viewNote').onclick=()=>openNoteViewer(id);$('#editNote').onclick=()=>openQuickNote(n);if($('#taskify'))$('#taskify').onclick=()=>{state.tasks.push({id:uid(),title:n.title||n.text,date:n.date||isoDate(new Date()),done:false,createdAt:nowISO(),auto:false,timing:'終日'});save();closeModal();render();toast('タスクにしました')};$('#deleteNote').onclick=()=>confirmDeleteNote(id)}
function displayMultiline(text){return esc(text||'').replace(/\n/g,'<br>')}
function openNoteViewer(id){const n=state.notes.find(x=>x.id===id);if(!n)return;if(n.type==='dailyReport')return openReportViewer(n);if(n.type==='meeting')return openMeetingViewer(n);openModal(`<div class="viewer-head"><button class="secondary" id="closeViewer">閉じる</button><div class="viewer-actions"><button class="secondary" id="editViewer">編集</button><button class="danger" id="deleteViewer">削除</button></div></div><article class="note-viewer"><div class="note-viewer-type">${esc(labelType(n.type))}</div><h1>${esc(noteDisplayTitle(n))}</h1><div class="note-viewer-meta">${esc(n.date||'')}・更新 ${new Date(n.updatedAt||n.createdAt).toLocaleString('ja-JP')}</div><div class="note-viewer-body">${displayMultiline(n.text)}</div></article>`, 'note-viewer');$('#closeViewer').onclick=closeModal;$('#editViewer').onclick=()=>openQuickNote(n);$('#deleteViewer').onclick=()=>confirmDeleteNote(id)}
function openReportViewer(n){const data=n.reportData||{};const sections=REPORT_FIELDS.filter(([k])=>(data[k]||'').trim()).map(([k,l])=>`<section class="report-view-section"><h3>${esc(l)}</h3><div>${displayMultiline(data[k])}</div></section>`).join('');const next=(data.next||[]).filter(Boolean);openModal(`<div class="viewer-head"><button class="secondary" id="closeViewer">閉じる</button><div class="viewer-actions"><button class="secondary" id="editViewer">編集</button><button class="danger" id="deleteViewer">削除</button></div></div><article class="report-viewer"><header><div class="note-viewer-type">日報</div><h1>${esc(n.title||reportTitleForDate(n.date))}</h1>${data.score?`<div class="report-score">自己評価 ${esc(data.score)}／10</div>`:''}</header>${sections}${next.length?`<section class="report-view-section"><h3>明日やること</h3><ol>${next.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>`:''}${!sections&&!next.length?'<div class="empty">記入内容はありません</div>':''}</article>`, 'note-viewer');$('#closeViewer').onclick=closeModal;$('#editViewer').onclick=()=>openQuickNote(n);$('#deleteViewer').onclick=()=>confirmDeleteNote(n.id)}
function reportTitleForDate(date){const d=new Date(date+'T12:00:00');return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日 日報`}
const REPORT_FIELDS=[['goal','今日の目標'],['actions','今日行ったこと'],['results','実績・結果'],['good','良かった点'],['improve','改善点・反省'],['staffRelation','スタッフとの関わり'],['insight','成功事例・気づき'],['consult','店長への報告・相談']];
function reportText(data){return [...REPORT_FIELDS.map(([k,l])=>`【${l}】\n${data[k]||''}`),`【明日やること】\n${(data.next||[]).filter(Boolean).join('\n')}`,`【自己評価】\n${data.score||''}/10`].join('\n\n')}
function loadReportDraft(date){try{return JSON.parse(localStorage.getItem(REPORT_DRAFT_STORE)||'{}')[date]||null}catch{return null}}
function saveReportDraft(date,draft){try{const all=JSON.parse(localStorage.getItem(REPORT_DRAFT_STORE)||'{}');all[date]=draft;localStorage.setItem(REPORT_DRAFT_STORE,JSON.stringify(all))}catch{}}
function clearReportDraft(date){try{const all=JSON.parse(localStorage.getItem(REPORT_DRAFT_STORE)||'{}');delete all[date];localStorage.setItem(REPORT_DRAFT_STORE,JSON.stringify(all))}catch{}}
function collectReportEditorData(){const data={};$$('[data-report-field]').forEach(x=>data[x.dataset.reportField]=x.value);data.next=$$('.next-task-input').map(x=>x.value);data.score=$('#reportScore')?.value||'';data.addTomorrowTasks=!!$('#addTomorrowTasks')?.checked;return data}
function openQuickNote(existing=null){
 const initialType=existing?.type||'inbox';
 openModal(`<div class="note-editor-head"><button class="secondary note-editor-close" id="cancel">閉じる</button><h2>${existing?'メモを編集':'メモを追加'}</h2><button class="primary note-editor-save" id="saveNote">保存</button></div><div class="grid2 note-editor-options"><div class="field"><label>種類</label><select id="noteType"><option value="inbox">受信箱</option><option value="normal">通常メモ</option><option value="staff">スタッフメモ</option><option value="dailyReport">日報</option><option value="meeting">MTG</option></select></div><div class="field"><label>日付</label><input type="date" id="noteDate" value="${existing?.date||isoDate(new Date())}"></div></div><div id="noteEditorDynamic" class="note-editor-dynamic"></div><div class="danger-note note-editor-options">個人情報・電話番号・契約情報は入力しないでください。</div>`, 'note-editor');
 $('#noteType').value=initialType;$('#cancel').onclick=closeModal;
 const renderDynamic=()=>{const type=$('#noteType').value,date=$('#noteDate').value||isoDate(new Date()),box=$('#noteEditorDynamic');
  if(type==='dailyReport'){const draft=!existing?loadReportDraft(date):null;const data=existing?.type==='dailyReport'?(existing.reportData||{}):(draft?.data||{});const next=data.next||['','',''];box.innerHTML=`<div class="draft-status" id="draftStatus">${draft?'下書きを復元しました':'入力内容は自動保存されます'}</div><div class="field note-editor-options"><label>タイトル</label><input id="reportTitle" value="${esc(existing?.type==='dailyReport'?(existing.title||reportTitleForDate(date)):(draft?.title||reportTitleForDate(date)))}"></div><div class="report-grid">${REPORT_FIELDS.map(([k,l])=>`<div class="field report-field"><label>${l}</label><textarea data-report-field="${k}">${esc(data[k]||'')}</textarea></div>`).join('')}<div class="field report-field"><label>明日やること</label>${[0,1,2].map(i=>`<input class="next-task-input" value="${esc(next[i]||'')}">`).join('')}<label class="check-row"><input type="checkbox" id="addTomorrowTasks" ${data.addTomorrowTasks?'checked':''}> 翌日のタスクに追加</label></div><div class="field report-field"><label>自己評価</label><select id="reportScore"><option value="">未選択</option>${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${String(data.score||'')===String(i+1)?'selected':''}>${i+1}/10</option>`).join('')}</select></div></div>`;}
  else if(type==='meeting'){renderMeetingEditor(box,existing,date);}
  else{box.innerHTML=`<div class="field note-editor-body"><textarea id="quickText">${esc(existing?.type!=='dailyReport'&&existing?.type!=='meeting'?(existing?.text||''):'')}</textarea></div><div class="field note-editor-options" id="staffField"><label>スタッフ名（任意）</label><input id="staffName" value="${esc(existing?.staff||'')}"></div>`;setTimeout(()=>$('#quickText')?.focus(),50);}
 };
 $('#noteType').onchange=()=>{renderDynamic();bindReportAutosave();bindMeetingAutosave()};$('#noteDate').onchange=()=>{const was=$('#noteType').value;renderDynamic();if(was==='dailyReport'&&$('#reportTitle'))$('#reportTitle').value=reportTitleForDate($('#noteDate').value);bindReportAutosave();bindMeetingAutosave()};renderDynamic();bindReportAutosave();bindMeetingAutosave();
 function bindReportAutosave(){if($('#noteType').value!=='dailyReport')return;const handler=()=>{const date=$('#noteDate').value,title=$('#reportTitle')?.value||reportTitleForDate(date),data=collectReportEditorData();saveReportDraft(date,{title,data,savedAt:nowISO()});if($('#draftStatus'))$('#draftStatus').textContent='下書きを自動保存しました'};$$('#noteEditorDynamic input,#noteEditorDynamic textarea,#noteEditorDynamic select').forEach(x=>x.addEventListener('input',handler));}
 function bindMeetingAutosave(){if($('#noteType').value!=='meeting')return;const handler=()=>{const d=collectMeetingEditorData();localStorage.setItem('worknote_meeting_draft_'+($('#noteDate').value||date),JSON.stringify(d));const x=$('#meetingDraftStatus');if(x)x.textContent='下書きを自動保存しました'};$$('#noteEditorDynamic input,#noteEditorDynamic textarea,#noteEditorDynamic select').forEach(x=>x.addEventListener('input',handler));}
 $('#saveNote').onclick=()=>{const type=$('#noteType').value,date=$('#noteDate').value;let addedCount=0;
  if(type==='dailyReport'){const data=collectReportEditorData();REPORT_FIELDS.forEach(([k])=>data[k]=(data[k]||'').trim());data.next=(data.next||[]).map(x=>x.trim());const title=$('#reportTitle').value.trim()||reportTitleForDate(date),text=reportText(data);if(existing){existing.title=title;existing.text=text;existing.type=type;existing.date=date;existing.reportData=data;existing.staff='';existing.updatedAt=nowISO()}else state.notes.push({id:uid(),title,text,type,date,reportData:data,staff:'',pinned:false,archived:false,createdAt:nowISO(),updatedAt:nowISO()});clearReportDraft(date);if(data.addTomorrowTasks){addedCount=data.next.filter(Boolean).length;const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+1);const tomorrow=isoDate(d);data.next.filter(Boolean).forEach(title=>{if(!state.tasks.some(t=>t.date===tomorrow&&t.title===title))state.tasks.push({id:uid(),title,date:tomorrow,done:false,createdAt:nowISO(),auto:false,timing:'終日',priority:'中'})})}}
  else if(type==='meeting'){const m=collectMeetingEditorData();if(!m.title.trim())return toast('MTGタイトルを入力してください');const text=meetingText(m);const target=existing||{id:uid(),createdAt:nowISO(),pinned:false,archived:false};Object.assign(target,{title:m.title.trim(),text,type:'meeting',date,meetingData:m,staff:'',updatedAt:nowISO()});if(!existing)state.notes.push(target);const created=createMeetingLinkedItems(target);localStorage.removeItem('worknote_meeting_draft_'+date);save();closeModal();runAIAutomation(true,{source:'meeting',noteId:target.id});render();toast(`MTGを保存しました${created.tasks?`・タスク${created.tasks}件`:''}${created.event?'・次回予定を登録':''}`);return;}
  else{const text=$('#quickText').value.trim();if(!text)return toast('内容を入力してください');if(existing){existing.title='';existing.text=text;existing.type=type;existing.date=date;existing.staff=$('#staffName').value.trim();existing.updatedAt=nowISO();delete existing.reportData;delete existing.meetingData}else state.notes.push({id:uid(),text,type,date,staff:$('#staffName').value.trim(),pinned:false,archived:false,createdAt:nowISO(),updatedAt:nowISO()});}
  save();closeModal();runAIAutomation(true,{source:type,noteId:existing?.id});render();if(addedCount)toast(`日報を保存し、明日のタスクを${addedCount}件登録しました`,'明日のタスクを見る',()=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+1);selectedDate=isoDate(d);switchView('calendar')},5000);else toast(type==='dailyReport'?'日報を保存しました':'メモを保存しました');};
}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let cells='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=isoDate(d),shift=shiftByDate(key),tasks=state.tasks.filter(t=>t.date===key),events=state.events.filter(e=>e.date===key);cells+=`<button class="day ${d.getMonth()!==m?'other':''} ${key===isoDate(new Date())?'today':''} ${key===selectedDate?'selected':''}" data-date="${key}"><div class="day-num">${d.getDate()}</div><div class="day-shift">${shift?esc(shift.name):''}</div><div class="day-count">${tasks.length?`✓${tasks.filter(t=>t.done).length}/${tasks.length}`:''}</div>${events.length?'<div class="dots">'+events.slice(0,3).map(()=>'<i class="dot"></i>').join('')+'</div>':''}</button>`}
 const dTasks=state.tasks.filter(t=>t.date===selectedDate),dEvents=state.events.filter(e=>e.date===selectedDate),selShift=shiftByDate(selectedDate);
 $('#view-calendar').innerHTML=`<div class="calendar-head"><button id="prevMonth">‹</button><h2>${y}年${m+1}月</h2><button id="nextMonth">›</button></div><div class="calendar"><div class="weekdays">${'日月火水木金土'.split('').map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells}</div></div><section class="section day-detail"><div class="section-head"><h2>${selectedDate.replaceAll('-','/')} ${selShift?'・'+selShift.name:''}</h2><button class="link-btn" id="addEvent">＋追加</button></div>${dEvents.map(e=>`<div class="card"><strong>${esc(e.title)}</strong><div class="small">${esc(e.time||'終日')}・予定${e.detail?'・'+esc(e.detail):''}</div></div>`).join('')}${dTasks.map(taskHTML).join('')||(!dTasks.length&&!dEvents.length?'<div class="empty">この日の予定・タスクはありません</div>':'')}</section>`;
 $('#prevMonth').onclick=()=>{calCursor.setMonth(m-1);renderCalendar()};$('#nextMonth').onclick=()=>{calCursor.setMonth(m+1);renderCalendar()};$$('[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar()});$('#addEvent').onclick=()=>openEventModal(selectedDate);bindTaskButtons()}
function openEventModal(date){
 openModal(`<h2>予定・タスクを追加</h2><div class="field"><label>種類</label><select id="entryType"><option value="event">予定</option><option value="task">タスク</option></select></div><div id="entryFields"></div><div class="btn-row"><button class="secondary" id="cancel">キャンセル</button><button class="primary" id="saveEntry">保存</button></div>`);
 const draw=()=>{const task=$('#entryType').value==='task';$('#entryFields').innerHTML=`<div class="field"><label>${task?'タスク名':'予定名'}</label><input id="entryTitle"></div><div class="grid2"><div class="field"><label>日付</label><input type="date" id="entryDate" value="${date}"></div>${task?`<div class="field"><label>タイミング</label><select id="entryTiming"><option>終日</option><option>出勤時</option><option>昼</option><option>退勤前</option></select></div>`:`<div class="field"><label>時間</label><input type="time" id="entryTime"></div>`}</div>${task?`<div class="field"><label>優先度</label><select id="entryPriority"><option>高</option><option selected>中</option><option>低</option></select></div>`:''}<div class="field"><label>詳細</label><textarea id="entryDetail"></textarea></div>`};
 $('#entryType').onchange=draw;draw();$('#cancel').onclick=closeModal;$('#saveEntry').onclick=()=>{const title=$('#entryTitle').value.trim();if(!title)return toast('内容を入力してください');const d=$('#entryDate').value,detail=$('#entryDetail').value.trim(),isTask=$('#entryType').value==='task';if(isTask){state.tasks.push({id:uid(),title,date:d,done:false,createdAt:nowISO(),auto:false,timing:$('#entryTiming').value,priority:$('#entryPriority').value,detail})}else state.events.push({id:uid(),title,date:d,time:$('#entryTime').value,detail,createdAt:nowISO()});save();closeModal();render();toast(isTask?'タスクを保存しました':'予定を保存しました')};
}
function renderAI(){runAIAutomation(false);const open=state.ai.inbox.filter(x=>x.status==='open');
 $('#view-ai').innerHTML=`<div class="ai-dashboard"><div class="viewer-head"><div><h1>AI副店長補佐</h1><p class="small">予定・タスク・メモ・日報・MTGを自動確認しています。</p></div><div class="viewer-actions"><button class="secondary" id="aiChatBtn">AIチャット</button><button class="secondary" id="aiRulesBtn">記憶ルール</button></div></div><div class="ai-status-row"><span>動作：${state.ai.mode==='geminiDirect'?'Gemini直接接続':'端末内スマート管理'}</span><span>状態：${esc(state.ai.mode==='geminiDirect'?(state.ai.connectionStatus||'未接続'):'端末内で動作中')}</span><span>最終確認：${state.ai.lastRun?new Date(state.ai.lastRun).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):'未実行'}</span></div>${state.ai.lastError?`<div class="warning">${esc(state.ai.lastError)}。端末内スマート管理は継続しています。</div>`:''}${open.map(aiInboxHTML).join('')||'<div class="empty">現在、対応が必要な項目はありません</div>'}</div>`;
 $('#aiChatBtn').onclick=openAIChat;$('#aiRulesBtn').onclick=openAIRules;$$('[data-ai-done]').forEach(b=>b.onclick=()=>{const x=state.ai.inbox.find(a=>a.id===b.dataset.aiDone);if(x)x.status='done';save();renderAI()});$$('[data-ai-action]').forEach(b=>b.onclick=()=>executeAIAction(b.dataset.aiAction,b.dataset.aiId));
}
function renderSettings(){$('#view-settings').innerHTML=`<div class="card settings-card" data-setting="shift"><div class="settings-icon">▦</div><div><h3>勤務・シフト</h3><p>月間登録、CSV取込、勤務種類</p></div><button>›</button></div><div class="card settings-card" data-setting="rules"><div class="settings-icon">↻</div><div><h3>自動タスク</h3><p>出勤日ごとの継続業務</p></div><button>›</button></div><div class="card settings-card" data-setting="ai"><div class="settings-icon">AI</div><div><h3>AI副店長補佐</h3><p>自動化、判断ルール、API接続</p></div><button>›</button></div><div class="card settings-card" data-setting="profile"><div class="settings-icon">✎</div><div><h3>表示・プロフィール</h3><p>名前、表示設定</p></div><button>›</button></div><div class="card settings-card" data-setting="update"><div class="settings-icon">⟳</div><div><h3>アプリ更新</h3><p>最新版を確認して更新・現在 v${APP_VERSION}</p></div><button>›</button></div><div class="card settings-card" data-setting="data"><div class="settings-icon">⇩</div><div><h3>データ管理</h3><p>バックアップ、復元、CSV出力</p></div><button>›</button></div><div class="card settings-card" data-setting="notification"><div class="settings-icon">◉</div><div><h3>通知</h3><p>通知全体・自動タスク別のON／OFF</p></div><button>›</button></div><div class="danger-note">WORKNOTEは個人用メモです。お客様の氏名・電話番号・契約情報などの個人情報は保存しないでください。</div>`;$$('[data-setting]').forEach(x=>x.onclick=()=>({shift:openShiftSettings,rules:openRules,ai:openAISettings,profile:openProfile,update:openAppUpdate,data:openData,notification:openNotifications}[x.dataset.setting])())}
function openShiftSettings(){openModal(`<h2>勤務・シフト</h2><div class="btn-row"><button class="primary" id="csvImport">CSV取込</button><button class="secondary" id="manualShift">手入力</button></div><section class="section"><h3>シフト種類</h3>${state.shiftTypes.map(s=>`<div class="list-row"><i style="width:12px;height:12px;border-radius:50%;background:${s.color}"></i><div class="grow"><strong>${esc(s.name)}</strong><div class="small">${s.start?`${s.start}〜${s.end}`:'休日'}</div></div><button class="secondary" data-edit-shift="${s.id}">編集</button></div>`).join('')}</section><button class="secondary" id="shiftTemplate" style="width:100%;margin-top:10px">CSVテンプレートを保存</button>`);$('#csvImport').onclick=()=>importCSV();$('#manualShift').onclick=()=>openManualShift();$('#shiftTemplate').onclick=downloadShiftTemplate;$$('[data-edit-shift]').forEach(b=>b.onclick=()=>openShiftTypeEdit(b.dataset.editShift))}
function openManualShift(){const month=isoDate(new Date()).slice(0,7);openModal(`<h2>シフトを手入力</h2><div class="field"><label>日付</label><input type="date" id="shiftDate" value="${month}-01"></div><div class="field"><label>勤務</label><select id="shiftType">${state.shiftTypes.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="btn-row"><button class="secondary" id="cancel">キャンセル</button><button class="primary" id="saveShift">登録</button></div>`);$('#cancel').onclick=closeModal;$('#saveShift').onclick=()=>{const d=$('#shiftDate').value;state.shifts[d]=$('#shiftType').value;reconcileDate(d);closeModal();render();toast('シフトを登録しました')}}
function openShiftTypeEdit(id){const s=state.shiftTypes.find(x=>x.id===id);openModal(`<h2>シフト種類を編集</h2><div class="field"><label>名称</label><input id="stName" value="${esc(s.name)}"></div><div class="grid2"><div class="field"><label>開始</label><input type="time" id="stStart" value="${s.start}"></div><div class="field"><label>終了</label><input type="time" id="stEnd" value="${s.end}"></div></div><div class="field"><label>表示色</label><input type="color" id="stColor" value="${s.color}"></div><button class="primary" id="saveST" style="width:100%">保存</button>`);$('#saveST').onclick=()=>{s.name=$('#stName').value.trim();s.start=$('#stStart').value;s.end=$('#stEnd').value;s.color=$('#stColor').value;save();closeModal();render();toast('保存しました')}}
function importCSV(){const input=$('#fileInput');input.accept='.csv,text/csv';input.onchange=async()=>{const text=await input.files[0].text();const rows=parseCSV(text);if(!rows.length)return toast('CSVを読み込めませんでした');openCSVPreview(rows);input.value=''};input.click()}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.length<2)return[];const head=lines[0].split(',').map(x=>x.trim());return lines.slice(1).map(line=>{const vals=line.split(',').map(x=>x.trim());return Object.fromEntries(head.map((h,i)=>[h,vals[i]||'']))}).filter(r=>r.date)}
function openCSVPreview(rows){const normalized=rows.map(r=>{const name=r.shift||r.shift_type||r.type;const st=state.shiftTypes.find(s=>s.name===name||s.id===name);return {date:r.date,shiftId:st?.id||'',name:name||'不明'}});openModal(`<h2>シフト取込プレビュー</h2>${normalized.map((r,i)=>`<div class="list-row"><div class="grow"><strong>${esc(r.date)}</strong><div class="small">${esc(r.name)}</div></div><select data-csv-i="${i}">${state.shiftTypes.map(s=>`<option value="${s.id}" ${s.id===r.shiftId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div>`).join('')}<div class="btn-row"><button class="secondary" id="cancel">キャンセル</button><button class="primary" id="applyCSV">この内容で登録</button></div>`);$('#cancel').onclick=closeModal;$('#applyCSV').onclick=()=>{normalized.forEach((r,i)=>{const id=$(`[data-csv-i="${i}"]`).value;state.shifts[r.date]=id;reconcileDate(r.date)});save();closeModal();render();toast(`${normalized.length}日分を登録しました`)}}
function downloadShiftTemplate(){download('worknote_shift_template.csv','date,shift,start_time,end_time,note\n2026-08-01,早番,09:30,18:30,\n2026-08-02,遅番,11:00,20:00,\n2026-08-03,休み,,,')}
function openRules(){openModal(`<h2>自動タスク設定</h2>${state.rules.map(r=>`<div class="list-row"><label class="switch"><input type="checkbox" data-rule-toggle="${r.id}" ${r.enabled?'checked':''}><i></i></label><div class="grow"><strong>${esc(r.title)}</strong><div class="small">${scopeLabel(r.scope)}・${esc(r.timing)}</div></div><button class="secondary" data-rule-edit="${r.id}">編集</button></div>`).join('')}<button class="primary" id="addRule" style="width:100%;margin-top:12px">＋自動タスクを追加</button>`);$$('[data-rule-toggle]').forEach(x=>x.onchange=()=>{const r=state.rules.find(a=>a.id===x.dataset.ruleToggle);r.enabled=x.checked;Object.keys(state.shifts).forEach(reconcileDate);save()});$$('[data-rule-edit]').forEach(x=>x.onclick=()=>openRuleEdit(x.dataset.ruleEdit));$('#addRule').onclick=()=>openRuleEdit()}
function scopeLabel(s){return s==='work'?'毎出勤日':s==='daily'?'毎日':(state.shiftTypes.find(x=>x.id===s)?.name||s)}
function openRuleEdit(id=null){const r=id?state.rules.find(x=>x.id===id):{title:'',enabled:true,scope:'work',timing:'退勤前',notify:false};openModal(`<h2>${id?'自動タスクを編集':'自動タスクを追加'}</h2><div class="field"><label>タスク名</label><input id="ruleTitle" value="${esc(r.title)}"></div><div class="grid2"><div class="field"><label>対象</label><select id="ruleScope"><option value="work">毎出勤日</option><option value="daily">毎日</option>${state.shiftTypes.filter(s=>s.id!=='off').map(s=>`<option value="${s.id}">${esc(s.name)}のみ</option>`).join('')}</select></div><div class="field"><label>タイミング</label><select id="ruleTiming"><option>出勤時</option><option>昼</option><option>退勤前</option><option>終日</option></select></div></div><div class="list-row"><div class="grow"><strong>端末へ通知</strong><div class="small">設定したタイミングに未完了なら通知</div></div><label class="switch"><input type="checkbox" id="ruleNotify" ${r.notify?'checked':''}><i></i></label></div><div class="btn-row">${id?'<button class="danger" id="deleteRule">削除</button>':''}<button class="primary" id="saveRule">保存</button></div>`);$('#ruleScope').value=r.scope;$('#ruleTiming').value=r.timing;$('#saveRule').onclick=()=>{const title=$('#ruleTitle').value.trim();if(!title)return toast('タスク名を入力してください');if(id){r.title=title;r.scope=$('#ruleScope').value;r.timing=$('#ruleTiming').value;r.notify=$('#ruleNotify').checked}else state.rules.push({id:uid(),title,enabled:true,scope:$('#ruleScope').value,timing:$('#ruleTiming').value,notify:$('#ruleNotify').checked});Object.keys(state.shifts).forEach(reconcileDate);save();closeModal();render();toast('保存しました')};if($('#deleteRule'))$('#deleteRule').onclick=()=>{state.rules=state.rules.filter(x=>x.id!==id);state.tasks=state.tasks.filter(t=>t.ruleId!==id||t.done||t.manuallyEdited);save();closeModal();render();toast('削除しました')}}
function openProfile(){openModal(`<h2>表示・プロフィール</h2><div class="field"><label>表示名</label><input id="profileName" value="${esc(state.profile.name)}"></div><button class="primary" id="saveProfile" style="width:100%">保存</button>`);$('#saveProfile').onclick=()=>{state.profile.name=$('#profileName').value.trim()||'ヒガ';save();closeModal();render();toast('保存しました')}}
function openData(){openModal(`<h2>データ管理</h2><div class="warning">端末やブラウザのデータを消すと記録も消える可能性があります。定期的にバックアップしてください。</div><button class="card" id="backup" style="width:100%;text-align:left"><strong>バックアップを保存</strong><div class="small">全データをJSONで保存</div></button><button class="card" id="restore" style="width:100%;text-align:left"><strong>バックアップから復元</strong><div class="small">復元前に内容を確認</div></button><button class="card" id="exportTasks" style="width:100%;text-align:left"><strong>タスク履歴をCSV出力</strong></button><button class="danger" id="resetAll" style="width:100%">全データを初期化</button>`);$('#backup').onclick=()=>{state.settings.lastBackup=nowISO();save();download(`worknote_backup_${isoDate(new Date())}.json`,JSON.stringify(state,null,2));toast('バックアップを保存しました')};$('#restore').onclick=restoreBackup;$('#exportTasks').onclick=exportTasks;$('#resetAll').onclick=()=>{if(confirm('すべてのデータを削除します。元に戻せません。')){state=clone(DEFAULT);save();closeModal();render();toast('初期化しました')}}}
function restoreBackup(){const input=$('#fileInput');input.accept='.json,application/json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(!data.tasks||!data.notes||!data.settings)throw Error();if(confirm(`タスク${data.tasks.length}件、メモ${data.notes.length}件を復元しますか？`)){state=data;save();closeModal();render();toast('復元しました')}}catch{toast('正しいバックアップではありません')}input.value=''};input.click()}
function exportTasks(){const rows=[['date','title','status','completed_at','source','carried_from'],...state.tasks.map(t=>[t.date,t.title,t.done?'done':'open',t.doneAt||'',t.auto?'auto':'manual',t.carriedFrom||''])];download(`worknote_tasks_${isoDate(new Date())}.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'))}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function notificationStatus(){if(!('Notification'in window))return 'この端末では非対応';return Notification.permission==='granted'?'許可済み':Notification.permission==='denied'?'端末設定で拒否中':'未設定'}
async function showDeviceNotification(title,body,tag='worknote',url='./?view=home'){if(!('Notification'in window)||Notification.permission!=='granted')return false;try{const reg=swRegistration||await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag,renotify:true,icon:'./icon-192.png',badge:'./icon-192.png',data:{url},vibrate:[180,80,180]});return true}catch(error){console.error('Notification failed:',error);return false}}
function openNotifications(){const masterOn=state.settings.notificationMaster!==false;openModal(`<h2>通知</h2><div class="card"><strong>端末の通知権限：${notificationStatus()}</strong><div class="small" style="margin-top:6px">通知全体・自動タスク・日報リマインドをこの画面で設定できます。</div></div><div class="list-row"><div class="grow"><strong>WORKNOTEの通知を使用</strong><div class="small">OFFにすると、下の設定に関係なくすべて停止</div></div><label class="switch"><input type="checkbox" id="notificationMaster" ${masterOn?'checked':''}><i></i></label></div><div class="section-head" style="margin-top:16px"><h2 style="font-size:16px">日報リマインド</h2></div><div class="list-row"><div class="grow"><strong>出勤日の未入力通知</strong><div class="small">当日の日報が未保存の場合だけ通知</div></div><label class="switch"><input type="checkbox" id="reportReminderEnabled" ${state.settings.reportReminderEnabled!==false?'checked':''}><i></i></label></div><div class="field"><label>通知時刻</label><input type="time" id="reportReminderTime" value="${esc(state.settings.reportReminderTime||'22:00')}"></div><div class="section-head" style="margin-top:16px"><h2 style="font-size:16px">自動タスク別</h2></div>${state.rules.map(r=>`<div class="list-row"><div class="grow"><strong>${esc(r.title)}</strong><div class="small">${scopeLabel(r.scope)}・${esc(r.timing)}（${reminderLabelForRule(r)}）</div></div><label class="switch"><input type="checkbox" data-notify-rule="${r.id}" ${r.notify?'checked':''} ${!r.enabled?'disabled':''}><i></i></label></div>`).join('')||'<div class="empty">自動タスクがありません</div>'}<button class="primary" id="requestNotify" style="width:100%;margin-top:14px">通知を許可する</button><button class="secondary" id="testNotify" style="width:100%;margin-top:10px">テスト通知を送る</button><div class="warning" style="margin-top:12px">Android側でWORKNOTEを強制停止した場合や省電力制限が強い場合、通知が遅れることがあります。</div>`);$('#notificationMaster').onchange=e=>{state.settings.notificationMaster=e.target.checked;save();toast(e.target.checked?'通知全体をONにしました':'通知全体をOFFにしました')};$('#reportReminderEnabled').onchange=e=>{state.settings.reportReminderEnabled=e.target.checked;save();toast(`日報通知を${e.target.checked?'ON':'OFF'}にしました`)};$('#reportReminderTime').onchange=e=>{state.settings.reportReminderTime=e.target.value||'22:00';save();toast('日報の通知時刻を変更しました')};$$('[data-notify-rule]').forEach(x=>x.onchange=()=>{const r=state.rules.find(a=>a.id===x.dataset.notifyRule);if(!r)return;r.notify=x.checked;save();toast(`${r.title}の通知を${x.checked?'ON':'OFF'}にしました`)});$('#requestNotify').onclick=async()=>{if(!('Notification'in window))return toast('この端末では通知を利用できません');const p=await Notification.requestPermission();state.settings.notifications=p==='granted';if(p==='granted')state.settings.notificationMaster=true;save();toast(p==='granted'?'通知を許可しました':'通知は許可されませんでした');openNotifications()};$('#testNotify').onclick=async()=>{if(Notification.permission!=='granted')return toast('先に通知を許可してください');const ok=await showDeviceNotification('WORKNOTE テスト通知','通知機能は正常に動作しています。','worknote-test-'+Date.now());toast(ok?'テスト通知を送信しました':'通知の送信に失敗しました')}}
function reminderLabelForRule(rule){if(rule.timing==='出勤時')return 'シフト開始時刻';if(rule.timing==='昼')return '13:00';if(rule.timing==='退勤前')return '退勤30分前';return '10:00'}
function reminderTimeFor(task,shift){if(task.timing==='出勤時')return shift?.start||'09:30';if(task.timing==='昼')return '13:00';if(task.timing==='退勤前'){if(!shift?.end)return '18:00';const [h,m]=shift.end.split(':').map(Number);const d=new Date(2000,0,1,h,m-30);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}return '10:00'}
async function checkTaskNotifications(){if(!state.settings.notifications||state.settings.notificationMaster===false||!('Notification'in window)||Notification.permission!=='granted')return;const date=isoDate(new Date()),shift=shiftByDate(date),now=`${pad(new Date().getHours())}:${pad(new Date().getMinutes())}`;state.settings.notificationLog=state.settings.notificationLog||{};for(const task of state.tasks.filter(t=>t.date===date&&!t.done&&t.auto)){const rule=state.rules.find(r=>r.id===task.ruleId);if(!rule?.notify)continue;const due=reminderTimeFor(task,shift),key=`${date}:${task.id}:${due}`;if(now>=due&&!state.settings.notificationLog[key]){const ok=await showDeviceNotification('WORKNOTE 未完了タスク',task.title,`task-${task.id}`);if(ok){state.settings.notificationLog[key]=nowISO();save()}}}const cutoff=new Date();cutoff.setDate(cutoff.getDate()-14);for(const [key,value] of Object.entries(state.settings.notificationLog)){if(new Date(value)<cutoff)delete state.settings.notificationLog[key]}await checkReportNotification()}
function reportWorkday(date){const s=shiftByDate(date);if(!s)return false;return !/(OFF|休み|休日|希望休)/i.test(s.name||'')}
async function checkReportNotification(){if(!state.settings.notifications||state.settings.notificationMaster===false||state.settings.reportReminderEnabled===false||Notification.permission!=='granted')return;const date=isoDate(new Date());if(!reportWorkday(date))return;if(state.notes.some(n=>n.type==='dailyReport'&&n.date===date))return;const now=`${pad(new Date().getHours())}:${pad(new Date().getMinutes())}`,due=state.settings.reportReminderTime||'22:00',key=`report:${date}:${due}`;state.settings.notificationLog=state.settings.notificationLog||{};if(now>=due&&!state.settings.notificationLog[key]){const ok=await showDeviceNotification('今日の日報が未入力です','1日の振り返りを記録しましょう。',`daily-report-${date}`,`./?action=daily-report&date=${date}`);if(ok){state.settings.notificationLog[key]=nowISO();save()}}}


const MTG_TYPES=['店舗ミーティング','個別面談','実績会議','朝礼・終礼','その他'];
function renderMeetingEditor(box,existing,date){let draft={};try{draft=JSON.parse(localStorage.getItem('worknote_meeting_draft_'+date)||'{}')}catch{}const m=existing?.meetingData||draft||{};const quick=m.quick||[];box.innerHTML=`<div class="draft-status" id="meetingDraftStatus">${Object.keys(draft).length&&!existing?'下書きを復元しました':'会議中の入力は自動保存されます'}</div><div class="meeting-basic"><div class="field"><label>MTGタイトル</label><input id="meetingTitle" value="${esc(m.title||'')}"></div><div class="grid2"><div class="field"><label>参加者</label><input id="meetingPeople" value="${esc(m.people||'')}"></div><div class="field"><label>場所</label><input id="meetingPlace" value="${esc(m.place||'')}"></div></div><div class="field"><label>種類</label><select id="meetingType">${MTG_TYPES.map(x=>`<option ${m.kind===x?'selected':''}>${x}</option>`).join('')}</select></div></div><section class="quick-capture"><h3>会議中クイック記録</h3><div class="quick-tags">${[['decision','決定'],['task','タスク'],['important','重要'],['hold','保留']].map(([k,l],i)=>`<button type="button" class="quick-tag ${i===0?'active':''}" data-qtype="${k}">${l}</button>`).join('')}</div><div class="quick-entry"><input id="quickMeetingInput" placeholder="短く入力"><button type="button" class="primary" id="addQuickMeeting">追加</button></div><div id="quickMeetingList">${quick.map((x,i)=>quickMeetingRow(x,i)).join('')}</div></section><details class="meeting-organize" ${existing?'open':''}><summary>議事録を整理する</summary><div class="field"><label>今回の目的</label><textarea id="mtgPurpose">${esc(m.purpose||'')}</textarea></div><div class="field"><label>現状・事実</label><textarea id="mtgFacts">${esc(m.facts||'')}</textarea></div><div class="field"><label>主な意見・共有事項</label><textarea id="mtgOpinions">${esc(m.opinions||'')}</textarea></div><div class="field"><label>決定事項</label><textarea id="mtgDecisions">${esc(m.decisions||'')}</textarea></div><div class="field"><label>確認する数字</label><textarea id="mtgMetrics">${esc(m.metrics||'')}</textarea></div><div class="field"><label>未決事項・持ち越し</label><textarea id="mtgPending">${esc(m.pending||'')}</textarea></div><h3>実行タスク</h3><div id="meetingTasks">${(m.tasks||[]).map((x,i)=>meetingTaskEditor(x,i)).join('')}</div><button type="button" class="secondary" id="addMeetingTask">＋タスク追加</button><h3>次回MTG</h3><div class="field"><label>次回開催日</label><input type="date" id="nextMeetingDate" value="${esc(m.nextDate||'')}"></div><div class="field"><label>次回の議題</label><textarea id="nextMeetingTopic">${esc(m.nextTopic||'')}</textarea></div><label class="check-row"><input type="checkbox" id="addNextMeeting" ${m.addNextMeeting?'checked':''}> カレンダーへ終日予定として登録</label></details>`;
 let qtype='decision';$$('[data-qtype]').forEach(b=>b.onclick=()=>{$$('[data-qtype]').forEach(x=>x.classList.remove('active'));b.classList.add('active');qtype=b.dataset.qtype});$('#addQuickMeeting').onclick=()=>{const input=$('#quickMeetingInput'),v=input.value.trim();if(!v)return;const m=collectMeetingEditorData();m.quick.push({type:qtype,text:v});renderMeetingEditor(box,{meetingData:m},date)};bindMeetingDynamic(box)}
function bindMeetingDynamic(box){$('#addMeetingTask')?.addEventListener('click',()=>{$('#meetingTasks').insertAdjacentHTML('beforeend',meetingTaskEditor({},$$('.meeting-task-row').length))});$$('.remove-meeting-task',box).forEach(b=>b.onclick=()=>b.closest('.meeting-task-row').remove());$$('.remove-quick',box).forEach(b=>b.onclick=()=>{const i=Number(b.dataset.i),m=collectMeetingEditorData();m.quick.splice(i,1);renderMeetingEditor(box,{meetingData:m},$('#noteDate').value)});}
function quickMeetingRow(x,i){const labels={decision:'決定',task:'タスク',important:'重要',hold:'保留'};return `<div class="quick-record"><span class="quick-record-tag ${x.type}">${labels[x.type]||'記録'}</span><div>${esc(x.text)}</div><button type="button" class="remove-quick" data-i="${i}">×</button></div>`}
function meetingTaskEditor(x={},i=0){return `<div class="meeting-task-row card"><div class="field"><label>やること</label><input data-mtask="title" value="${esc(x.title||'')}"></div><div class="grid2"><div class="field"><label>担当者</label><input data-mtask="assignee" value="${esc(x.assignee||'')}"></div><div class="field"><label>期限日</label><input data-mtask="date" type="date" value="${esc(x.date||'')}"></div></div><div class="grid2"><div class="field"><label>優先度</label><select data-mtask="priority"><option ${x.priority==='高'?'selected':''}>高</option><option ${!x.priority||x.priority==='中'?'selected':''}>中</option><option ${x.priority==='低'?'selected':''}>低</option></select></div><label class="check-row"><input type="checkbox" data-mtask="notify" ${x.notify?'checked':''}> 通知</label></div><button type="button" class="danger remove-meeting-task">削除</button></div>`}
function collectMeetingEditorData(){const quick=$$('.quick-record').map(x=>({type:$('.quick-record-tag',x)?.classList[1]||'important',text:$('div',x)?.textContent||''}));const tasks=$$('.meeting-task-row').map(row=>({title:$('[data-mtask="title"]',row)?.value.trim()||'',assignee:$('[data-mtask="assignee"]',row)?.value.trim()||'',date:$('[data-mtask="date"]',row)?.value||'',priority:$('[data-mtask="priority"]',row)?.value||'中',notify:!!$('[data-mtask="notify"]',row)?.checked})).filter(x=>x.title);return{title:$('#meetingTitle')?.value||'',people:$('#meetingPeople')?.value||'',place:$('#meetingPlace')?.value||'',kind:$('#meetingType')?.value||MTG_TYPES[0],quick,purpose:$('#mtgPurpose')?.value||'',facts:$('#mtgFacts')?.value||'',opinions:$('#mtgOpinions')?.value||'',decisions:$('#mtgDecisions')?.value||quick.filter(x=>x.type==='decision').map(x=>x.text).join('\n'),metrics:$('#mtgMetrics')?.value||'',pending:$('#mtgPending')?.value||quick.filter(x=>x.type==='hold').map(x=>x.text).join('\n'),tasks:tasks.length?tasks:quick.filter(x=>x.type==='task').map(x=>({title:x.text,assignee:'',date:'',priority:'中',notify:false})),nextDate:$('#nextMeetingDate')?.value||'',nextTopic:$('#nextMeetingTopic')?.value||'',addNextMeeting:!!$('#addNextMeeting')?.checked}}
function meetingText(m){return `【目的】\n${m.purpose}\n\n【現状・事実】\n${m.facts}\n\n【主な意見】\n${m.opinions}\n\n【決定事項】\n${m.decisions}\n\n【実行タスク】\n${m.tasks.map(x=>`${x.title}（担当:${x.assignee||'未設定'}／期限:${x.date||'未設定'}）`).join('\n')}\n\n【確認する数字】\n${m.metrics}\n\n【未決事項】\n${m.pending}`}
function createMeetingLinkedItems(n){let tasks=0,event=false;const m=n.meetingData||{};(m.tasks||[]).forEach(x=>{if(!x.title||!x.date)return;if(!state.tasks.some(t=>t.title===x.title&&t.date===x.date)){state.tasks.push({id:uid(),title:x.title,date:x.date,done:false,createdAt:nowISO(),auto:false,timing:'終日',priority:x.priority||'中',assignee:x.assignee||'',notify:!!x.notify,sourceMeetingId:n.id});tasks++}});if(m.addNextMeeting&&m.nextDate&&m.nextTopic&&!state.events.some(e=>e.date===m.nextDate&&e.title===m.nextTopic)){state.events.push({id:uid(),title:m.nextTopic,date:m.nextDate,allDay:true,createdAt:nowISO(),sourceMeetingId:n.id});event=true}return{tasks,event}}
function openMeetingViewer(n){const m=n.meetingData||{};const sec=(title,val)=>val?.trim()?`<section class="report-view-section"><h3>${title}</h3><div>${displayMultiline(val)}</div></section>`:'';openModal(`<div class="viewer-head"><button class="secondary" id="closeViewer">閉じる</button><div class="viewer-actions"><button class="secondary" id="editViewer">編集</button><button class="danger" id="deleteViewer">削除</button></div></div><article class="report-viewer meeting-viewer"><header><div class="note-viewer-type">MTG</div><h1>${esc(n.title)}</h1><div class="note-viewer-meta">${esc(n.date)}・${esc(m.kind||'')} ${m.people?`・参加者 ${esc(m.people)}`:''}${m.place?`・${esc(m.place)}`:''}</div></header>${sec('今回の目的',m.purpose)}${sec('現状・事実',m.facts)}${sec('主な意見・共有事項',m.opinions)}${sec('決定事項',m.decisions)}${(m.tasks||[]).length?`<section class="report-view-section"><h3>実行タスク</h3>${m.tasks.map(x=>`<div class="meeting-task-view"><b>${esc(x.title)}</b><span>${esc(x.assignee||'担当未設定')}・${esc(x.date||'期限未設定')}・優先度 ${esc(x.priority||'中')}</span></div>`).join('')}</section>`:''}${sec('確認する数字',m.metrics)}${sec('未決事項・持ち越し',m.pending)}${m.nextDate||m.nextTopic?`<section class="report-view-section"><h3>次回MTG</h3><div>${esc(m.nextDate||'日付未定')}<br>${displayMultiline(m.nextTopic||'')}</div></section>`:''}</article>`,'note-viewer');$('#closeViewer').onclick=closeModal;$('#editViewer').onclick=()=>openQuickNote(n);$('#deleteViewer').onclick=()=>confirmDeleteNote(n.id)}
function aiItem(kind,title,body,actions=[]){const key=kind+'|'+title+'|'+isoDate(new Date());if(state.ai.inbox.some(x=>x.key===key&&x.status==='open'))return;state.ai.inbox.push({id:uid(),key,kind,kindLabel:{priority:'優先',warning:'注意',draft:'下書き',staff:'育成',report:'報告',weekly:'週報'}[kind]||'提案',title,body,actions,status:'open',createdAt:nowISO()})}
function runAIAutomation(force=false,context={}){if(!state.ai.enabled)return;const today=isoDate(new Date()),key=today+'|'+state.tasks.length+'|'+state.notes.length+'|'+state.events.length;if(!force&&state.ai.lastDigestKey===key)return;state.ai.lastDigestKey=key;state.ai.lastRun=nowISO();const todayTasks=state.tasks.filter(t=>t.date===today),overdue=state.tasks.filter(t=>!t.done&&t.date<today);if(overdue.length)aiItem('warning',`期限超過が${overdue.length}件あります`,overdue.slice(0,5).map(x=>`・${x.title}（${x.date}）`).join('\n'),[{type:'viewTasks'}]);const open=todayTasks.filter(t=>!t.done);if(open.length)aiItem('priority','今日の優先順位を整理しました',open.slice(0,3).map((x,i)=>`${i+1}. ${x.title}`).join('\n'),[{type:'acceptFocus',value:open[0]?.title||''}]);const latestReport=state.notes.filter(n=>n.type==='dailyReport').sort((a,b)=>(b.updatedAt||b.createdAt).localeCompare(a.updatedAt||a.createdAt))[0];if(latestReport){const d=latestReport.reportData||{};if((d.improve||'').trim())aiItem('draft','日報から改善行動を抽出しました',`改善点：${d.improve}\n推奨：明日の最優先タスクとして固定する`,[{type:'createTask',title:(d.next||[]).find(Boolean)||d.improve.split(/\n/)[0],date:nextWorkDate(today)||today}]);if((d.consult||'').trim())aiItem('report','店長報告の下書き候補があります',d.consult,[{type:'copy'}])}
 state.notes.filter(n=>n.type==='meeting').slice(-3).forEach(n=>{const m=n.meetingData||{},missing=(m.tasks||[]).filter(x=>!x.assignee||!x.date);if(missing.length)aiItem('warning',`${n.title}のタスク設定が未完了です`,missing.map(x=>`・${x.title}（${!x.assignee?'担当者 ':''}${!x.date?'期限':''}未設定）`).join('\n'),[{type:'editMeeting',id:n.id}])});
 const staff={};state.notes.filter(n=>n.type==='staff'&&n.staff).forEach(n=>{staff[n.staff]=staff[n.staff]||[];staff[n.staff].push(n.text)});Object.entries(staff).forEach(([name,items])=>state.ai.staffInsights[name]={summary:items.slice(-3).join('\n'),updatedAt:nowISO()});
 const weekStart=new Date();weekStart.setDate(weekStart.getDate()-6);const recentReports=state.notes.filter(n=>n.type==='dailyReport'&&new Date(n.date+'T12:00:00')>=weekStart);if(recentReports.length>=3)aiItem('weekly','直近7日間の週報を準備しました',`日報 ${recentReports.length}件／完了タスク ${state.tasks.filter(t=>t.done&&new Date(t.date+'T12:00:00')>=weekStart).length}件\n繰り返し確認すべき改善点：\n${recentReports.map(n=>n.reportData?.improve).filter(Boolean).slice(-3).map(x=>'・'+x).join('\n')}`);save();if(state.ai.mode==='geminiDirect'&&getGeminiApiKey())requestRemoteAI(context).catch(console.error)}
function getGeminiApiKey(){return localStorage.getItem(GEMINI_KEY_STORE)||''}
function setGeminiApiKey(value){const key=(value||'').trim();if(key)localStorage.setItem(GEMINI_KEY_STORE,key);else localStorage.removeItem(GEMINI_KEY_STORE)}
function aiSystemInstruction(isChat){return [
 'あなたはWORKNOTE専用のAI副店長補佐です。回答は日本語で簡潔かつ具体的にしてください。',
 '確認できない事実を作らず、記録にない人物・数字・期限を断定しないでください。',
 '顧客の個人情報は出力しないでください。スタッフへの人格評価ではなく、記録された行動と傾向だけを扱ってください。',
 '他スタッフへの指示、店長報告、削除や予定変更は確定せず、必ず候補として提示してください。',
 isChat?'ユーザーの修正意図を確認し、何を変更したかを短く返してください。':'優先順位、期限超過、日報改善、MTGの抜け、スタッフ育成、店長報告、週報のうち必要なものだけを返してください。'
].join('\n')}
const AI_ACTION_SCHEMA={type:'OBJECT',properties:{type:{type:'STRING',enum:['createTask','acceptFocus','viewTasks','editMeeting','copy']},title:{type:'STRING'},date:{type:'STRING'},value:{type:'STRING'},id:{type:'STRING'}},required:['type','title','date','value','id']};
const AI_ANALYSIS_SCHEMA={type:'OBJECT',properties:{items:{type:'ARRAY',maxItems:8,items:{type:'OBJECT',properties:{kind:{type:'STRING',enum:['priority','warning','draft','staff','report','weekly']},title:{type:'STRING'},body:{type:'STRING'},actions:{type:'ARRAY',maxItems:3,items:AI_ACTION_SCHEMA}},required:['kind','title','body','actions']}}},required:['items']};
const AI_CHAT_SCHEMA={type:'OBJECT',properties:{reply:{type:'STRING'}},required:['reply']};
const AI_TEST_SCHEMA={type:'OBJECT',properties:{status:{type:'STRING',enum:['ok']},message:{type:'STRING'}},required:['status','message']};
async function callGeminiDirect({input,schema,isChat=false}){const apiKey=getGeminiApiKey();if(!apiKey)throw Error('Gemini APIキーが未入力です');const model=state.ai.model||DEFAULT_GEMINI_MODEL;const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:aiSystemInstruction(isChat)}]},contents:[{role:'user',parts:[{text:input}]}],generationConfig:{responseMimeType:'application/json',responseSchema:schema}})});const data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data?.error?.message||`Gemini APIエラー（${res.status}）`);const text=(data?.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('').trim();if(!text)throw Error('Geminiから回答が返りませんでした');try{return JSON.parse(text)}catch{throw Error('GeminiのJSON応答を解析できませんでした')}}
async function requestRemoteAI(context={}){const payload={profile:state.profile,today:isoDate(new Date()),shift:shiftByDate(isoDate(new Date())),tasks:state.tasks.slice(-80),events:state.events.slice(-40),notes:state.notes.slice(-50).map(n=>({id:n.id,type:n.type,date:n.date,title:n.title,text:n.text,staff:n.staff})),rules:state.ai.rules,context};try{const data=await callGeminiDirect({input:`以下はWORKNOTEのデータです。保存済みルールを最優先し、今日の行動につながる提案を最大8件返してください。重複提案は避けてください。\n${JSON.stringify(payload)}`,schema:AI_ANALYSIS_SCHEMA});(data.items||[]).forEach(x=>aiItem(x.kind||'draft',x.title||'AI提案',x.body||'',x.actions||[]));state.ai.connectionStatus='接続済み';state.ai.lastError='';save();render();return data}catch(error){state.ai.connectionStatus='接続失敗';state.ai.lastError=error.message||'Gemini接続に失敗しました';save();render();throw error}}
function openAIDashboard(){closeModal();switchView('ai')}
function aiInboxHTML(x){return `<div class="card ai-inbox-item"><div class="ai-item-head"><span class="tag">${esc(x.kindLabel)}</span><button class="more-btn" data-ai-done="${x.id}">完了</button></div><h3>${esc(x.title)}</h3><div class="ai-body">${displayMultiline(x.body)}</div>${(x.actions||[]).map((a,i)=>`<button class="secondary ai-action" data-ai-action="${i}" data-ai-id="${x.id}">${a.type==='createTask'?'タスク登録':a.type==='acceptFocus'?'今日の重点に反映':a.type==='editMeeting'?'MTGを修正':'確認する'}</button>`).join('')}</div>`}
function executeAIAction(index,id){const item=state.ai.inbox.find(x=>x.id===id),a=item?.actions?.[Number(index)];if(!a)return;if(a.type==='createTask'&&a.title){state.tasks.push({id:uid(),title:a.title,date:a.date||isoDate(new Date()),done:false,createdAt:nowISO(),auto:false,timing:'終日',priority:'高',source:'ai'});toast('AI提案をタスク登録しました')}else if(a.type==='acceptFocus'){state.focus[isoDate(new Date())]=a.value;toast('今日の重点へ反映しました')}else if(a.type==='editMeeting'){const n=state.notes.find(x=>x.id===a.id);if(n)return openQuickNote(n)}item.status='done';save();render();openAIDashboard()}
function openAIChat(){openModal(`<div class="viewer-head"><button class="secondary" id="backAI">戻る</button><h3>AIとのすり合わせ</h3></div><div class="ai-chat-log">${state.ai.chat.slice(-30).map(x=>`<div class="chat-bubble ${x.role}">${displayMultiline(x.text)}</div>`).join('')}</div><div class="field"><textarea id="aiChatInput" placeholder="例：イベントのスタッフは店舗施策の対象にしない"></textarea></div><div class="field"><label>反映範囲</label><select id="aiMemoryScope"><option value="once">今回だけ</option><option value="theme">このテーマで今後も</option><option value="global">全体ルールとして保存</option></select></div><button class="primary" id="sendAIChat" style="width:100%">送信</button>`,'note-viewer');$('#backAI').onclick=openAIDashboard;$('#sendAIChat').onclick=async()=>{const text=$('#aiChatInput').value.trim();if(!text)return;const scope=$('#aiMemoryScope').value;state.ai.chat.push({role:'user',text,at:nowISO()});if(scope!=='once')state.ai.rules.push({id:uid(),scope,text,createdAt:nowISO()});let reply=`了解しました。${scope==='global'?'全体ルール':scope==='theme'?'このテーマのルール':'今回の修正'}として反映します。`;if(state.ai.mode==='geminiDirect'&&getGeminiApiKey()){try{const d=await callGeminiDirect({isChat:true,schema:AI_CHAT_SCHEMA,input:`ユーザーがAIの認識や提案を修正しています。反映範囲（今回だけ・テーマ・全体）を踏まえ、修正後の認識を短く確認してください。操作は勝手に実行しないでください。\n${JSON.stringify({message:text,scope,rules:state.ai.rules,context:state.ai.inbox.filter(x=>x.status==='open')})}`});reply=d.reply||reply}catch{reply+=' Gemini接続に失敗したため、ルール保存のみ完了しました。'}}state.ai.chat.push({role:'assistant',text:reply,at:nowISO()});save();openAIChat()}}

function openAIRules(){openModal(`<h2>AIが覚えているルール</h2>${state.ai.rules.map(x=>`<div class="card rule-memory"><div><span class="tag">${x.scope==='global'?'全体':x.scope==='theme'?'テーマ':'今回'}</span><p>${esc(x.text)}</p></div><button class="danger" data-del-rule="${x.id}">削除</button></div>`).join('')||'<div class="empty">保存されたルールはありません</div>'}<button class="secondary" id="backAI" style="width:100%">戻る</button>`);$('#backAI').onclick=openAIDashboard;$$('[data-del-rule]').forEach(b=>b.onclick=()=>{state.ai.rules=state.ai.rules.filter(x=>x.id!==b.dataset.delRule);save();openAIRules()})}
function openAISettings(){const hasKey=!!getGeminiApiKey();openModal(`<h2>AI副店長補佐</h2><div class="list-row"><div class="grow"><strong>AI管理を使用</strong><div class="small">アプリ内データを自動確認</div></div><label class="switch"><input type="checkbox" id="aiEnabled" ${state.ai.enabled?'checked':''}><i></i></label></div><div class="field"><label>動作モード</label><select id="aiMode"><option value="local">端末内スマート管理（API不要）</option><option value="geminiDirect">Gemini直接接続</option></select></div><div class="field"><label>Gemini APIキー</label><input id="geminiApiKey" type="password" autocomplete="off" placeholder="AIza..." value=""><div class="small">${hasKey?'APIキーはこの端末に保存済みです。変更時だけ再入力してください。':'Google AI Studioで作成したAPIキーを入力してください。'} GitHubには保存されません。</div></div><div class="field"><label>モデル</label><select id="geminiModel"><option value="gemini-3.1-flash-lite">Gemini 3.1 Flash-Lite（推奨）</option><option value="gemini-3.5-flash">Gemini 3.5 Flash</option></select></div><div class="danger-note">直接接続ではAPIキーをこの端末のブラウザ内に保存します。共有端末では使用しないでください。</div><div class="card"><strong>接続状態</strong><div class="small">${esc(state.ai.mode==='geminiDirect'?(state.ai.connectionStatus||'未接続'):'端末内モード')}${state.ai.model?`・${esc(state.ai.model)}`:''}</div>${state.ai.lastError?`<div class="warning">${esc(state.ai.lastError)}</div>`:''}</div><div class="field"><label>自動化レベル</label><select id="aiLevel"><option value="1">1：提案のみ</option><option value="2">2：下書きまで自動</option><option value="3">3：安全な自分用タスクは自動登録</option></select></div><div class="btn-row"><button class="secondary" id="testAIConnection">接続だけテスト</button><button class="primary" id="saveAISettings">保存して分析</button></div>`);$('#aiMode').value=state.ai.mode;$('#aiLevel').value=String(state.ai.automationLevel||2);$('#geminiModel').value=state.ai.model||DEFAULT_GEMINI_MODEL;const readSettings=()=>{state.ai.enabled=$('#aiEnabled').checked;state.ai.mode=$('#aiMode').value;state.ai.model=$('#geminiModel').value;state.ai.endpoint='';state.ai.automationLevel=Number($('#aiLevel').value);const entered=$('#geminiApiKey').value.trim();if(entered)setGeminiApiKey(entered);save()};$('#testAIConnection').onclick=async()=>{readSettings();if(state.ai.mode!=='geminiDirect')return toast('Gemini直接接続を選択してください');if(!getGeminiApiKey())return toast('Gemini APIキーを入力してください');const button=$('#testAIConnection');button.disabled=true;button.textContent='接続確認中…';try{const d=await callGeminiDirect({input:'接続確認として status に ok、message に 接続できました を入れてください。',schema:AI_TEST_SCHEMA});state.ai.connectionStatus='接続済み';state.ai.lastError='';save();toast(d.message||'Geminiへの接続を確認しました');openAISettings()}catch(e){state.ai.connectionStatus='接続失敗';state.ai.lastError=e.message||'接続に失敗しました';save();toast('接続に失敗しました');openAISettings()}};$('#saveAISettings').onclick=async()=>{readSettings();if(state.ai.mode==='geminiDirect'&&!getGeminiApiKey())return toast('Gemini APIキーを入力してください');closeModal();render();runAIAutomation(true,{source:'settings-test'});toast('AI設定を保存しました')}}

function switchView(v){currentView=v;render();window.scrollTo(0,0)}
function openModal(html,mode='default'){const modal=$('#modal');modal.classList.toggle('note-editor-modal',mode==='note-editor');modal.classList.toggle('note-viewer-modal',mode==='note-viewer');$('#modalContent').innerHTML=html;modal.classList.remove('hidden')}
function closeModal(){const modal=$('#modal');modal.classList.add('hidden');modal.classList.remove('note-editor-modal','note-viewer-modal');$('#modalContent').innerHTML=''}
function globalSearch(){openModal(`<h2>検索</h2><div class="field"><input id="globalQ" placeholder="メモ・タスク・予定を検索"></div><div id="searchResults"></div>`);$('#globalQ').oninput=e=>{const q=e.target.value.trim().toLowerCase();if(!q)return $('#searchResults').innerHTML='';const notes=state.notes.filter(n=>(n.text||'').toLowerCase().includes(q)||(n.title||'').toLowerCase().includes(q)).slice(0,10),tasks=state.tasks.filter(t=>t.title.toLowerCase().includes(q)).slice(0,10),events=state.events.filter(x=>x.title.toLowerCase().includes(q)).slice(0,10);$('#searchResults').innerHTML=[...notes.map(n=>`<div class="card"><strong>メモ</strong><div>${esc(noteDisplayTitle(n))}</div><div class="small">${n.date}</div></div>`),...tasks.map(t=>`<div class="card"><strong>${t.done?'✓ ':''}タスク</strong><div>${esc(t.title)}</div><div class="small">${t.date}</div></div>`),...events.map(x=>`<div class="card"><strong>予定</strong><div>${esc(x.title)}</div><div class="small">${x.date}</div></div>`)].join('')||'<div class="empty">見つかりません</div>'}}
async function openAppUpdate(){
 openModal(`<h2>アプリ更新</h2><div class="card"><strong>現在のバージョン</strong><div class="small">v${APP_VERSION}</div></div><p class="small">新しいバージョンが公開されているか確認します。メモやタスクのデータは消えません。</p><button class="primary" id="checkUpdateBtn" style="width:100%">最新版を確認</button>`);
 $('#checkUpdateBtn').onclick=async()=>{
  const button=$('#checkUpdateBtn');button.disabled=true;button.textContent='確認中…';
  try{
   if(!('serviceWorker' in navigator))throw new Error('unsupported');
   const registration=swRegistration || await navigator.serviceWorker.getRegistration('./');
   if(!registration)throw new Error('not-registered');
   await registration.update();
   const waiting=registration.waiting;
   if(waiting){button.textContent='更新しています…';waiting.postMessage({type:'SKIP_WAITING'});return;}
   if(registration.installing){
    button.textContent='更新を準備中…';
    registration.installing.addEventListener('statechange',()=>{
     if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});
     else if(registration.installing?.state==='activated'){updateReloading=true;location.reload();}
    });
    return;
   }
   button.textContent='最新版です';toast('WORKNOTEは最新版です');
  }catch(error){console.error('Update check failed:',error);button.disabled=false;button.textContent='もう一度確認';toast('更新確認に失敗しました');}
 };
}
function watchServiceWorker(registration){
 swRegistration=registration;
 registration.addEventListener('updatefound',()=>{
  const worker=registration.installing;if(!worker)return;
  worker.addEventListener('statechange',()=>{
   if(worker.state==='installed' && navigator.serviceWorker.controller)toast('新しい更新を利用できます');
  });
 });
}
navigator.serviceWorker?.addEventListener('controllerchange',()=>{
 if(updateReloading)return;updateReloading=true;location.reload();
});
$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#quickAdd').onclick=()=>openQuickNote();$('#searchBtn').onclick=globalSearch;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
function startApp(){
 try{
  $('#splash')?.classList.add('hidden');
  $('#app')?.classList.remove('hidden');
  render();
  runAIAutomation(true,{source:'startup'});
  checkTaskNotifications();
  const params=new URLSearchParams(location.search);
  if(params.get('action')==='quick-note')openQuickNote();if(params.get('action')==='daily-report'){const date=params.get('date')||isoDate(new Date());const existing=state.notes.find(n=>n.type==='dailyReport'&&n.date===date);openQuickNote(existing||null);setTimeout(()=>{if(!existing&&$('#noteType')){$('#noteType').value='dailyReport';$('#noteDate').value=date;$('#noteType').dispatchEvent(new Event('change'))}},50)}
  if(params.get('view')&&['home','notes','calendar','ai','settings'].includes(params.get('view')))switchView(params.get('view'));
 }catch(error){
  console.error('WORKNOTE startup failed:',error);
  const splash=$('#splash');
  if(splash){splash.innerHTML='<h1>WORKNOTE</h1><p>起動処理で問題が発生しました。ページを再読み込みしてください。</p><button onclick="location.reload()">再読み込み</button>';}
 }
}

document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){checkTaskNotifications();runAIAutomation(false,{source:'resume'})}});
setInterval(checkTaskNotifications,30000);
window.addEventListener('load',()=>{
 setTimeout(startApp,250);
 if('serviceWorker' in navigator){
  navigator.serviceWorker.register('./sw.js', {scope:'./',updateViaCache:'none'})
   .then(async registration=>{
    watchServiceWorker(registration);
    try{await registration.update()}catch(error){console.warn('Service Worker update failed:',error)}
   })
   .catch(error=>console.error('Service Worker registration failed:',error));
 }
});
